spring.application.name=projeto-aoe

spring.datasource.url=jdbc:mysql://localhost:3306/db_aoe?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
